# What is NumPy?

[NumPy](https://numpy.org/doc/stable/user/absolute_beginners.html) is a Python library for efficient numerical data storage and computation.
It is the fundamental building block of many other scientific libraries (such as pandas, scikit-learn and many others).

It is important to be able to use its basic functionalities, and to understand the basic principles underneath, in order to be able to use other libraries efficiently.

| ⚠️ Keep in mind |
|:-|
| While NumPy uses Python, coding with NumPy and coding with Python rely on two different approaches. Mixing the two will likely result in poor performances. If you want your code to be efficient, you'll want to understand the NumPy way of doing things. We'll cover this together in the workshop! |

In [1]:
# Let's select this cell (click on it) and execute it (shift+enter) to
# import numpy so that it's available for the rest of the notebook
import numpy as np

## When to use NumPy & Scientific Python rather than pure Python?

Pure Python is great at handling very heterogeneous data and offers a lot of flexibility.
It really shines when writing scripts, for Web API, and for designing CLI tools.

However, if you are handling large amounts of numerical data, NumPy is probably more suited for the task.
If you are doing scientific computing, data analysis, or machine learning, if you use `pandas` or `scikit-learn`, you are in the world of NumPy, and you should avoid using Python data structures and paradigms in that case, to avoid performance issues.

Don't worry if it still seems a bit cryptic now, we will see plenty of examples in the next sections.

## NumPy arrays vs Python lists

NumPy's base building blocks are **arrays**, which are more or less vectors or matrices. They can seem similar to Python lists on the first glance.

In [2]:
a = [1, 2, 3, 4, 5]  # a Python list
b = np.array([1, 2, 3, 4, 5])  # a NumPy array

There are some key differences between the two:
- Python lists may contain any type of data, and are optimized to iterate on elements one by one; they are very flexible but not very efficient for numerical computation;
- NumPy arrays are less flexible: they operate on a single data type, and have a predetermined size; however, they may handle multidimensional data, and are optimized for performing numerical operations on large datasets.

The rest of this notebook covers the specifics in more detail.

### Data types
Python lists can contain elements of different types, for exemple, you can have a list where one element is an integer, the next one is a string, and the following one is a boolean.

In [3]:
my_list = [1, "foo", True]

On the other hand, NumPy arrays require all elements to have the same data type (or `dtype`), and this type must be compatible with NumPy: numerical or boolean.
NumPy provides data types for handling non-numeric data such as strings or arbitrary Python objects, but it is less efficient. NumPy is really shining for handling numerical data.

In [4]:
my_int_array = np.array([1, 2, 3])
print("my_int_array.dtype", my_int_array.dtype)
my_bool_array = np.array([True, False, True])
print("my_bool_array.dtype", my_bool_array.dtype)

my_int_array.dtype int64
my_bool_array.dtype bool


Python lists are extremely flexible, and can contain any kind of Python objects, including other lists, dictionaries, or even more complex objects.

In [5]:
my_list = [1, "foo", True]

class MyComplexDatastructure:
    code: int = 418
    message: str = "I'm a teapot"

my_complex_list = [1, lambda x: x+2, [1, 2, 3], {"some_key": "some_value"}, MyComplexDatastructure()]

### Dimensionality
Python lists are essentially one-dimensional objects, but you can simulate multi-dimensionality by nesting lists.
There will not be any checks to ensure that all of our nested lists have the same length, and it is cumbersome to access elements in dimensions other than the first one.

In [6]:
my_2d_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(my_2d_list)
# get the first row
print("first row:", my_2d_list[0])
# get the second column
print("second column", [row[1] for row in my_2d_list])
# note that this 2D list is still valid
my_2d_list2 = [[1, 2], [3, 4, 5], [6, 7, 8, 9]]
print("a weird but valid nested list\n", my_2d_list2)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
first row: [1, 2, 3]
second column [2, 5, 8]
a weird but valid nested list
 [[1, 2], [3, 4, 5], [6, 7, 8, 9]]


NumPy arrays can have one, two or more dimensions, and it's equally easy to access all of them.
All lines have the same length, and all rows have the same length.

In [7]:
my_matrix = np.array([[1, 2], [3, 4], [5, 6]])
print(my_matrix)
print("my matrix shape:", my_matrix.shape)
# get the first row
print("first row:", my_matrix[0])
# get the second column
print("second column", my_matrix[:, 1])


[[1 2]
 [3 4]
 [5 6]]
my matrix shape: (3, 2)
first row: [1 2]
second column [2 4 6]


In [8]:
# this is not a valid matrix
my_matrix2 = np.array([[1, 2], [3, 4, 5], [6, 7, 8, 9]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

### Computation
Advanced Python data structures are optimised for lazy computing: list comprehension and generators allow you to only perform a computation when it's needed. It is great for filtering streams of data that might not fit in memory.
```python
import pathlib
result = [line.split("]", 1)[1].lower() for line in pathlib.Path("logs.txt").open() if line.startswith("[ERROR]")]
```

In [9]:
# compute the square of all multiples of 17 between 0 and 100
[x * x for x in range(100) if not(x % 17)]

[0, 289, 1156, 2601, 4624, 7225]

NumPy is optimised for vectorized operations: performing computations on a whole array (or a whole column / row) at once.
It requires a bit of adjustment to think about operations in a vectorized way, but we will see that it yields a significant performance gain.

In [10]:
arr = np.array([1, 2, 3, 4, 5])
# compute the square of the whole array in one go
np.power(arr, 2)

array([ 1,  4,  9, 16, 25])

### Memory allocation
Python lists and NumPy arrays might seem like similar data structures from the outside, but many of their differences can be explained by how they allocate memory.
Python lists are perfectly fine with adding elements at the end of the list as you go, and popping elements from the beginning or the end of the list.

In [11]:
my_list = [1, 2, 3, 4]
print("my list", my_list)
element = my_list.pop()
print(f"I take the last element {element} from the list {my_list}")
my_list.append(5)
my_list.append(6)
print("I can add new elements to my list", my_list)
element2 = my_list.pop(0)
print(f"I take the first element {element2} from the list {my_list}")

my list [1, 2, 3, 4]
I take the last element 4 from the list [1, 2, 3]
I can add new elements to my list [1, 2, 3, 5, 6]
I take the first element 1 from the list [2, 3, 5, 6]


NumPy arrays allocate their memory when they are created, as a contiguous block of memory. This means that is you need to add more elements to the array, everything will be copied to a new memory location, which is very slow.
You can change the content of each "cell" of the array (as long as you respect the data type), but it is costly to add new elements.
We will see how you can create arrays soon.

In [12]:
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(my_array)
my_array[0, 0] = 0
print(my_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 2 3]
 [4 5 6]
 [7 8 9]]



## Summary

| Python lists                                      | NumPy arrays                                                     |
|---------------------------------------------------|------------------------------------------------------------------|
| Heterogeneous data and all data types supported   | All data must have the same type: `uint8`, `float64`, `bool`.... |
| One dimensional only                              | All dimensions of a matrix can be accessed easily                |
| Optimised for lazy computing (element by element) | Optimised for vectorized operations (whole array at once)        |
| Flexible memory allocation (but slow)             | Predetermined memory allocation (but fast)                       |