# 2. Basic indexing and slicing

Now that we know how to create NumPy arrays, let's see how we can access its elements.

First, we need to import numpy to use it in this notebook.

In [1]:
import numpy as np

## One-dimensional arrays

One-dimensional NumPy arrays can be accessed like you would do with Python list: using `[]`.

The indexing starts at `0`. The first element is `my_array[0]`, the second `my_array[1]`, ...
You can also start the indexing from the end with negative integers: the last element is `[-1]`, the one before is `[-2]` and so on.

In [2]:
my_array = np.arange(1, 13)
print(my_array)

print("first element", my_array[0])
print("second element", my_array[1])
print("last element", my_array[-1])

[ 1  2  3  4  5  6  7  8  9 10 11 12]
first element 1
second element 2
last element 12


## Slices
NumPy arrays also support slicing (taking multiple consecutive values at once), like Python lists: you can use two values separated by `: ` to get a slice of the array.

In [3]:
my_array[2:5]

array([3, 4, 5])

The indexes are zero-based, the first element is included, and the last one excluded. Don't worry if that seems a bit confusing, it does requires some practice to get used to it!

A famous joke amongst programmers is that the two hardest things to get right in programming are timezones, cache invalidation, and off-by-one errors!

The first index of a slice can be omitted if it's zero, and the last one if you want to go to the end of the array.

In [4]:
# get the first 3 elements
my_array[:3]

array([1, 2, 3])

In [5]:
# get the last 10
my_array[-10:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Slices can also have a third element: the increment: `first_element_included:last_element_excluded:step`.

In [6]:
# get one element out of two, between the second and the tenth elements (both included)
my_array[1:11:2]

array([ 2,  4,  6,  8, 10])

Bounds can also be omitted if you want to take the whole array.

In [7]:
# get one element every third, for the whole array
my_array[::3]

array([ 1,  4,  7, 10])

You can fetch multiple values at once by passing a list of indices. You will have 2 sets of brackets.

In [8]:
my_array = np.arange(1, 13)
print("array", my_array)
print("result", my_array[[1, 3, 8, 8, 5]])

array [ 1  2  3  4  5  6  7  8  9 10 11 12]
result [2 4 9 9 6]


Instead of a list of indices, it can be an array of indices.

In [9]:
indices = np.arange(3, 9, 2)
print("array", my_array)
print("indices", indices)
print("result", my_array[indices])

array [ 1  2  3  4  5  6  7  8  9 10 11 12]
indices [3 5 7]
result [4 6 8]


## Assigning new values
It is possible to assign a new value to any element of an array. 

In [10]:
print(my_array)
my_array[3] = 9
print(my_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  9  5  6  7  8  9 10 11 12]


The assigned value will be converted to the `dtype` of the array, so ensure it's compatible.

In [11]:
print(my_array)
my_array[5] = 4.5
print(my_array)

[ 1  2  3  9  5  6  7  8  9 10 11 12]
[ 1  2  3  9  5  4  7  8  9 10 11 12]


In particular, you might get unexpected behaviours due to integer overflow. Recent versions of NumPy now check for that.

In [12]:
uint_array = np.zeros(3, dtype=np.uint8)
print(uint_array)
uint_array[2] = -1
print(uint_array)

[0 0 0]
[  0   0 255]


/var/folders/h8/sfpff4yj3_1938xc18jhxhww0000gn/T/ipykernel_35025/2265864639.py:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -1 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  uint_array[2] = -1


It is also possible to assign several values at the same time.

In [13]:
my_array = np.arange(1, 13)
print(my_array)
my_array[2:8] = 42
print(my_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2 42 42 42 42 42 42  9 10 11 12]


In [14]:
my_array = np.arange(1, 13)
print(my_array)
my_array[4:8] = np.array([154, 23, 17, 95])
print(my_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[  1   2   3   4 154  23  17  95   9  10  11  12]


## Multi-dimensional arrays

For arrays with more than one dimension, you can use the same way of indexing for each dimension; each dimension is separated by a `,`.

In [15]:
my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
my_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
# get the second element of the first row
my_array[0, 1]

2

It is also possible to get a whole dimension (row or column). `:` can be used as a placeholder to get all elements in that dimension.
(It's actually a slice where both limits are omitted, hence defaulting to the first and the last element!)

In [17]:
print(my_array[0])  # get the first row
print(my_array[0, :])  # this is equivalent

[1 2 3 4]
[1 2 3 4]


In [18]:
# get the column (second dimension)
my_array[:, 0]

array([1, 5, 9])

This works with slices as well.

In [19]:
my_array[1:3, 0]

array([5, 9])

You can even take a slice in multiple dimensions at once.

In [20]:
my_array[1:3, 2:4]

array([[ 7,  8],
       [11, 12]])

### Assigning values in multi-dimensional arrays
You can also assign values.

In [21]:
print("before")
print(my_array)
my_array[1, 2] = 42
print("after")
print(my_array)

before
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
after
[[ 1  2  3  4]
 [ 5  6 42  8]
 [ 9 10 11 12]]


You can assign values in multiple dimensions at once.

## Exercise

Create a 3 x 4 array full of 2, except the top right corner which should contain a 3.

There are several ways of doing that.

In [22]:
# uncomment and execute the following line if you want to load the solution
# %load ../solutions/exercise1.py