# 3. Shape and broadcasting

Every NumPy array has a `shape` attribute that controls how NumPy interprets the array. It is a tuple of as many elements as the number of dimensions of the array, and each element is an integer indicating the size of the array in that dimension.


In [1]:
import numpy as np
np.arange(5).shape

(5,)

In [2]:
my_2d_array = np.ones((2, 3))
my_2d_array.shape

(2, 3)

In [3]:
my_3d_array = np.ones((8, 10, 5))
my_3d_array.shape

(8, 10, 5)

No matter what is the shape of the array, the data in memory is still stored as a continuous block. That means that you can reshape an array without copying the data.
It is a different _view_ of the same data.

In [4]:
a = np.arange(12).reshape(3, 4)
print("a", a)
b = a.reshape(2, 6)
print("b", b)

a [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [5]:
a[0, 0] = 42
print("a", a)
# b is not a copy of a, just a different view of the same data
print("b", b)

a [[42  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b [[42  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


The new shape must have the same number of elements as the original array. You can use `-1` as a wild card for one of the dimensions, and NumPy will infer the correct value.

In [6]:
c = a.reshape(4, -1)
c

array([[42,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Amongst other things, you can transpose a matrix without copying the data.

In [7]:
my_matrix = np.arange(12).reshape(3, 4)
print(my_matrix)
print("transposed:")
print(my_matrix.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
transposed:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### Exercise
Starting from a range from 1 to 12, can you create an array where all odd numbers are in the first row and all even numbers in the second row?
```
[[1, 3, 5, 7, 9, 11],
 [2, 4, 6, 8, 10, 12]]
 ```

In [8]:
a = np.arange(1, 13)
...

In [9]:
# uncomment and execute the following line if you want to load the solution
# %load ../solutions/exercise2.py

## Broadcasting

When you want to make a simple operation with all the elements of an array
(e.g. multiply every element by 2), you can multiply the array itself by 2. By
a process called "broadcasting", NumPy will apply the operation to every
element of the array.

Broadcasting is the way Numpy handles the interaction of two arrays that may or
may not have the same dimensions. Scalars (i.e. numbers, bools, or single
values of any kind) can be though as arrays with a single value. Under the
hood, NumPy will find how to reshape the arrays to make the operation possible.

In [10]:
a = np.ones(5)
print(a)
print(a * 2)
print(a - 0.5)

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
[0.5 0.5 0.5 0.5 0.5]


The scalar (a number) is broadcasted to match the shape of the array; it will apply mathematical operations element-wise.

It also works with multi-dimensional arrays.

In [11]:
a = np.ones((3, 4))
print(a)
print(a * 2)
print(a + 1.8)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[2.8 2.8 2.8 2.8]
 [2.8 2.8 2.8 2.8]
 [2.8 2.8 2.8 2.8]]


The power of broadcasting is that you can perform operations with arrays of different shapes, as long as the shapes are compatible.

The most common use case is performing operations between a 2D-array and a (1D) vector: the length of the vector must match the number of columns of the 2D-array.

In [12]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
a * np.array([1, 10, 100, 1000])

array([[    0,    10,   200,  3000],
       [    4,    50,   600,  7000],
       [    8,    90,  1000, 11000]])

If the shape are not compatible, NumPy will raise a `ValueError`.

In [14]:
a * np.array([1, 10, 100])

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

## Vectors and arrays

The previous line raised an error, but it still feels like it should be possible to perform the operation row-wise. 
The problem is that one-dimensional arrays are interpreted by NumPy as "rows", and if you want to have a "column", you want an array with a shape `(1, N)`.

In [15]:
np.array([1, 10, 100]).shape

(3,)

You can add a dimension to the array by using `np.newaxis`.

In [16]:
column = np.array([1, 10, 100])[:, np.newaxis]
print(column)
print(column.shape)

[[  1]
 [ 10]
 [100]]
(3, 1)


You can also use `None` as a shortcut to add a new dimension. We've decided to use `np.newaxis` in this notebook to make it more explicit, but you will often see `None` in other people's code.

In [17]:
np.array([1, 10, 100])[:, None]

array([[  1],
       [ 10],
       [100]])

You can now perform row-wise operation between an array and a column vector.

In [18]:
a * np.array([1, 10, 100])[:, np.newaxis]

array([[   0,    1,    2,    3],
       [  40,   50,   60,   70],
       [ 800,  900, 1000, 1100]])

### Exercise

You have an array of distances between cities along a road, and you would like to get the matrix of pairwise distances between cities. 

*Hint:* you might want to use `np.abs` to get the absolute value of a number.

In [19]:
distances = np.array([98, 155, 267, 314, 495, 587, 618])
...

In [ ]:
# uncomment and execute the following line if you want to load the solution
# %load ../solutions/exercise3.py