# 4. Concatenation and stacking

`np.reshape` is helping you to rearrange data in an array, but without changing the number of elements.
Another typical need is creating a new array by concatenating several arrays together.

You can concatenate arrays sharing a common dimension using `np.concatenate`.
The `axis` argument specifies the dimension along which the arrays will be concatenated (0 for rows, 1 for columns).

In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
np.concatenate([a, a, a], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
np.concatenate([a, a], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [5]:
np.concatenate([a, np.ones((3, 1))], axis=1)

array([[ 0.,  1.,  2.,  3.,  1.],
       [ 4.,  5.,  6.,  7.,  1.],
       [ 8.,  9., 10., 11.,  1.]])

In [6]:
np.concatenate([a, np.ones((2, 4))], axis=0)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

Note that contrary to `reshape` that only change the view of the data without copying it, `concatenate` copies the data to a new array.
It's still fast because it can copy the memory block in one go, but it's something to keep in mind when working with large arrays.

In [7]:
b = np.concatenate([a, a], axis=1)
a[0, 0] = 42
b

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

Rather than remembering which axis is which, you can use np.vstack and np.hstack to stack arrays vertically (along the row axis) or horizontally (along the column axis) respectively.

In [8]:
a = np.arange(6).reshape(2, 3)
print(np.vstack([a, a]))
np.all(np.vstack([a, a]) == np.concatenate([a, a], axis=0))

[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]


True

In [9]:
print(np.hstack([a, a]))
np.all(np.hstack([a, a]) == np.concatenate([a, a], axis=1))

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]


True

## Concatenating vectors
If you are working with vectors, you have to keep in mind that they have only one dimension.
`np.concatenate` might not work as you are expecting, and it's safer to use `np.vstack`.

In [10]:
row = np.arange(1, 4)
# this will give a result you might not expect
np.concatenate([row, row], axis=0)

array([1, 2, 3, 1, 2, 3])

In [11]:
# this will fail
np.concatenate([row, row], axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [12]:
# this will work as expected
np.vstack([row, row])

array([[1, 2, 3],
       [1, 2, 3]])

If you want to stack arrays horizontally (each array being a new column), you can either convert them to column vectors with `np.newaxis` or use `np.column_stack`.

In [13]:
col1 = np.arange(1, 4)
col2 = np.full(3, 5)
print(col1, col2)

[1 2 3] [5 5 5]


In [14]:
# this is not the result you want
np.hstack([col1, col2])

array([1, 2, 3, 5, 5, 5])

In [15]:
# converting to column vectors works
np.hstack([col1[:, np.newaxis], col2[:, np.newaxis]])

array([[1, 5],
       [2, 5],
       [3, 5]])

In [16]:
# or using a specific function
np.column_stack([col1, col2])

array([[1, 5],
       [2, 5],
       [3, 5]])

### Exercise
Given the following array `a`, extract the first and the last column, revert the order of the last column and stack them side by side.
The resulting array should look like this:
```
[[ 0, 23],
[ 4, 19],
[ 8, 15],
[12, 11],
[16,  7],
[20,  3]]
```

_Hint_: remember that there are three parameters when you use a slice: start, stop, and step.

In [17]:
a = np.arange(24).reshape(6, 4)
print(a)
...

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


Ellipsis

In [ ]:
# uncomment and execute the following line if you want to load the solution
# %load ../solutions/exercise4.py