# 5. Advanced indexing

Slices are a very powerful tool which can allow you to access the elements of an array in a flexible way.
You can use a different increment for each dimension, for exemple, and select a different range.

In [1]:
import numpy as np

### Exercise

Given the following array, extract the elements following a zigzag pattern: (0, 0), (1, 1), (2,0), (3, 1), (4, 0), (5, 1), ...

You should get: `[ 0,  3,  4,  7,  8, 11, 12, 15, 16, 19, 20, 23]`

In [2]:
a = np.arange(24).reshape(-1, 2)
print(a)
...

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


Ellipsis

In [3]:
# uncomment and execute the following line if you want to load the solution
# %load ../solutions/exercise5.py

## Fancy indexing

NumPy arrays can be indexed with any array or list of integers, including with duplicated indices.
This is different from slicing, because it will create a copy of the data.

In [4]:
a = np.arange(10, 0, -1)
print(a)
a[[0, 1, 0, 1, 2, 4]]

[10  9  8  7  6  5  4  3  2  1]


array([10,  9, 10,  9,  8,  6])

This also works for multi-dimensional arrays, supports broadcasting and can be used to modify the array.

In [5]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
# reorder and duplicate lines
b[[0, 2, 1, 0]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [7]:
# reorder columns
b[:, [2, 0, 1, 3]]

array([[ 2,  0,  1,  3],
       [ 6,  4,  5,  7],
       [10,  8,  9, 11]])

Passing two lists of indices will extract the elements at the corresponding coordinates.

In [8]:
b[[0, 2, 1], [1, 2, 3]]
# extract the elements at (0, 1), (2, 2) and (1, 3)

array([ 1, 10,  7])

Note that this is different from slicing, because it will create a copy of the data.

In [9]:
a = np.arange(10, 0, -1)
print(a)
with_slicing = a[::2]
with_fancy_indexing = a[[0, 2, 4, 6, 8]]
print("with slicing", with_slicing)
print("with fancy indexing", with_fancy_indexing)
a[0] = 42
print("with slicing - this is a view of the original array", with_slicing)
print("with fancy indexing - this is a copy", with_fancy_indexing)

[10  9  8  7  6  5  4  3  2  1]
with slicing [10  8  6  4  2]
with fancy indexing [10  8  6  4  2]
with slicing - this is a view of the original array [42  8  6  4  2]
with fancy indexing - this is a copy [10  8  6  4  2]


### Exercise
Write a function that returns the corners of any 2D array.

Fill in the code skeleton, and then test it out with the various test cases.

In [10]:
def corners(a: np.ndarray) -> np.ndarray:
    # your code here
    return

In [11]:
# uncomment and execute the following line if you want to load the solution
# %load ../solutions/exercise6.py

In [12]:
# test cases
a = np.ones((4, 5))
print(a)
assert np.all(corners(a) == np.array([1, 1, 1, 1]))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


AssertionError: 

In [ ]:
b = np.arange(9).reshape(3, 3)
print(b)
assert np.all(corners(b) == np.array([0, 2, 6, 8]))

In [ ]:
c = np.arange(12).reshape(-1, 2)
print(c)
assert np.all(corners(c) == np.array([0, 1, 10, 11]))

## Boolean masks
One trick that is very useful when manipulating arrays is to leverage boolean masks.

A boolean mask is an array of the same shape as the original array, filled with boolean values. It is typically produced by applying a comparison operator to the array.

In [13]:
a = np.arange(12).reshape(3, 4)
mask = a <= 2
print(a)
print(mask)  # mask is a boolean array filled with True where the value of a is <= 2 and False elsewhere

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ True  True  True False]
 [False False False False]
 [False False False False]]


We can use a boolean mask to perform operations on a subset of the array.

In [14]:
a[mask] = 0
print(a)

[[ 0  0  0  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


It's usual to do both operations in a single line:

In [15]:
a[a > 5]  # Get me all the values where a > 5

array([ 6,  7,  8,  9, 10, 11])

Note: The opposite of a mask can be obtained by using the `~` operator

In [16]:
mask = (a > 2) & (a < 7)
print("         mask")
print(mask)
print("opposite mask")
print(~mask)

         mask
[[False False False  True]
 [ True  True  True False]
 [False False False False]]
opposite mask
[[ True  True  True False]
 [False False False  True]
 [ True  True  True  True]]


### Exercise
Replace all negative values of the array with 0.

In [17]:
a = np.random.normal(0, 1, (5, 4))
# your code here
...
assert np.all(a >= 0)

AssertionError: 

In [ ]:
# uncomment and execute the following line if you want to load the solution
# %load ../solutions/exercise7.py

## Sorting
NumPy provides a function that returns a sorted copy of an array.

In [18]:
a = np.array([3, 1, 2, 8, 47])
np.sort(a)

array([ 1,  2,  3,  8, 47])

Sometimes, this is not exactly what you need; `np.argsort` tells you in which order to take the indices of the array to sort it, and you can further manipulate the result.

In [19]:
sorted_indexes = np.argsort(a)
print(sorted_indexes)  # The smallest value has index 1, then 2, 0, 3, and the biggest element is the one at index 4

[1 2 0 3 4]


In [20]:
# sorting the array in reverse order
print(a[sorted_indexes[::-1]])

[47  8  3  2  1]


### Exercise
You have an array of 7 unsorted numbers, that represent notes given by a jury for an olympic event.
The lowest and highest notes should be removed, and return the remaining notes, sorted in ascending order.

In [21]:
notes = np.array([8, 7, 6, 9, 8, 4, 10])
...

In [ ]:
# uncomment and execute the following line if you want to load the solution
# %load ../solutions/exercise8.py

## Bonus exercise

Create a 8x8 checkboard (alternating 0s and 1s for black and white).
There are several ways to do this, using a boolean mask, fancy indexing or concatenation.

In [ ]:
# uncomment and execute the following line if you want to load the solution
# %load ../solutions/exercise9.py